version: '3.3'
services:
  web:
    container_name: appName
    restart: always
    build: .
    ports:
      - "3200:3200"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/backend/app

  login-database:
    image: mysql
    container_name: login-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Prueba
    ports:
      - "3306:3306"
    volumes:
      - login-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - login-network

volumes:
  login-data:
    driver: local

networks:
  login-network:
    driver: bridge